name: Mas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: |
          Expand-Archive -Path ngrok.zip -DestinationPath ngrok

      - name: Authenticate ngrok
        run: |
          .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create ngrok Configuration
        shell: pwsh
        run: |
          @"
          authtoken: $Env:NGROK_AUTH_TOKEN
          tunnels:
            rdp:
              proto: tcp
              addr: 3389
              region: eu
          "@ | Out-File -FilePath .\ngrok\ngrok.yml -Encoding utf8
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Terminal Services and Configure RDP
        shell: pwsh
        run: |
          # Разрешить подключения через RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          
          # Включить правило брандмауэра для RDP
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # Включить аутентификацию пользователей для RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          
          # Создать или обновить пользователя 'runneradmin' с заданным паролем
          $password = ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force
          if (Get-LocalUser -Name "runneradmin" -ErrorAction SilentlyContinue) {
              Set-LocalUser -Name "runneradmin" -Password $password
          } else {
              New-LocalUser -Name "runneradmin" -Password $password -FullName "Runner Admin" -Description "Admin user for RDP"
              Add-LocalGroupMember -Group "Administrators" -Member "runneradmin"
          }

      - name: Start ngrok Tunnel
        run: |
          .\ngrok\ngrok.exe start --all --config .\ngrok\ngrok.yml
