name: Setup RDP with Ngrok on Windows 11

on:
  push:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: self-hosted  # Используем self-hosted runner
    steps:
      - name: Скачивание Ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Распаковка Ngrok
        run: Expand-Archive ngrok.zip -DestinationPath .\ngrok

      - name: Аутентификация Ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Включение RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          # Создание пользователя (опционально)
          # Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force)

      - name: Запуск Ngrok для RDP
        run: .\ngrok\ngrok.exe tcp 3389
