name: macOS RDP with Ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Шаг 1: Скачиваем и распаковываем ngrok
    - name: Download Ngrok
      run: curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip

    - name: Extract Ngrok
      run: unzip ngrok.zip

    # Шаг 2: Аутентифицируемся в ngrok
    - name: Auth Ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # Шаг 3: Создаем нового пользователя для RDP
    - name: Create New User for RDP
      run: |
        sudo sysadminctl -addUser rdpuser -password "P@ssw0rd!" -admin
        sudo dscl . create /Users/rdpuser UserShell /bin/bash
        sudo dscl . create /Users/rdpuser RealName "RDP User"
        sudo dscl . create /Users/rdpuser UniqueID "510"
        sudo dscl . create /Users/rdpuser PrimaryGroupID 20
        sudo dscl . create /Users/rdpuser NFSHomeDirectory /Users/rdpuser
        sudo createhomedir -c -u rdpuser

    # Шаг 4: Включаем удаленное управление и разрешаем подключение по RDP
    - name: Enable Remote Management (ARD)
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -access -on -users rdpuser -privs -all -restart -agent -menu

    # Шаг 5: Открываем порт 3389 в брандмауэре
    - name: Open port 3389 in firewall
      run: |
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockApp /System/Library/CoreServices/RemoteManagement/ARDAgent.app
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on

    # Шаг 6: Создаем туннель через ngrok на порт 3389
    - name: Create Ngrok Tunnel for RDP
      run: ./ngrok tcp 3389
