name: Mas

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    
    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip

    - name: Ngrok Authentication
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Ngrok Config File (EU Region)
      run: |
        Add-Content -Path "$Env:USERPROFILE\.ngrok2\ngrok.yml" -Value "authtoken: $Env:NGROK_AUTH_TOKEN"
        Add-Content -Path "$Env:USERPROFILE\.ngrok2\ngrok.yml" -Value "region: eu"
    
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set Admin Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    
    - name: Create Tunnel (EU Server via Config)
      run: .\ngrok\ngrok.exe tcp 3389 --config "$Env:USERPROFILE\.ngrok2\ngrok.yml"

    - name: Optimize Network for RDP
      run: |
        # Установка приоритетов для QoS RDP, улучшение пинга
        New-NetQosPolicy -Name "RDP QoS" -IPProtocolMatchCondition "TCP" -DestinationPort 3389 -DSCPAction 46
