name: macOS RDP with Ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Download Ngrok
      run: curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip

    - name: Extract Ngrok
      run: unzip ngrok.zip

    - name: Auth Ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Management (ARD)
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -access -on -users runneradmin -privs -all -restart -agent -menu

    - name: Open Firewall for Remote Management
      run: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app

    - name: Set Password for runneradmin
      run: |
        sudo dscl . -passwd /Users/runneradmin "P@ssw0rd!"

    - name: Create Ngrok Tunnel for RDP
      run: ./ngrok tcp 3389
